version: '3.5'

services:
  voda-frontend:
    container_name: voda-frontend
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
