dist:
    - trusty

matrix:
    include:
        name: "Backend Local Unit Tests"
        script:
            - docker-compose -f backend/local.yml build
            - docker-compose run django flake8
            - docker-compose run django pytest
