dist:
    - trusty

language:
    - generic

matrix:
    include:
        name: "Backend Local Unit Tests"
        script:
            - docker-compose -f backend/local.yml build
            - docker-compose -f backend/local.yml run django flake8
            - docker-compose -f backend/local.yml run django pytest
