dist:
    - trusty

language:
    - generic

matrix:
    include:
        name: "Backend Local Unit Tests"
        script:
            - docker-compose -f backend/local.yml --log-level WARNING build
            - docker-compose -f backend/local.yml --log-level WARNING run django flake8
            - docker-compose -f backend/local.yml --log-level WARNING run django pytest -vv
