# Generated by Django 2.2 on 2019-05-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contaminants',
            fields=[
                ('contaminant_id', models.AutoField(primary_key=True, serialize=False)),
                ('contaminant_name', models.CharField(max_length=200)),
                ('health_guideline', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('legal_limit', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('national_avg', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('summary', models.TextField(null=True)),
                ('health_concerns', models.TextField(null=True)),
                ('long_health_concerns', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StateAvgLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_avg', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Contaminants')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States')),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('utility_name', models.CharField(max_length=200)),
                ('number_served', models.IntegerField()),
                ('rating', models.FloatField(null=True)),
                ('city', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Cities')),
                ('county', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Counties')),
                ('state', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States')),
            ],
        ),
        migrations.CreateModel(
            name='SourceLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contaminant_level', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Contaminants')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Sources')),
            ],
        ),
        migrations.AddField(
            model_name='counties',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States'),
        ),
        migrations.AddField(
            model_name='cities',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Counties'),
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States'),
        ),
    ]
