# Generated by Django 2.0.10 on 2019-03-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='State_Avg_Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_avg', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='contaminants',
            name='associated_conditions',
        ),
        migrations.RemoveField(
            model_name='contaminants',
            name='maximum_level',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='county',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='contaminants',
            name='contaminant_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaminants',
            name='health_concerns',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaminants',
            name='health_guideline',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaminants',
            name='legal_limit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaminants',
            name='long_health_concerns',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaminants',
            name='national_avg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaminants',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sources',
            name='number_served',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sources',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sources',
            name='utility_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contaminants',
            name='contaminant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sourcelevels',
            name='contaminant_level',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sources',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.State'),
        ),
        migrations.AddField(
            model_name='state_avg_levels',
            name='contaminant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Contaminants'),
        ),
        migrations.AddField(
            model_name='state_avg_levels',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.State'),
        ),
    ]
