# Generated by Django 2.2 on 2019-04-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
