# Generated by Django 2.2 on 2019-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
