# Generated by Django 2.2.1 on 2019-05-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='utility_name',
            field=models.CharField(max_length=500),
        ),
    ]
