# Generated by Django 2.2 on 2019-04-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0002_auto_20190429_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sources',
            old_name='score',
            new_name='rating',
        ),
    ]
