# Generated by Django 2.2.1 on 2019-05-01 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0002_auto_20190501_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Cities'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Counties'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States'),
        ),
    ]
