# Generated by Django 2.1.7 on 2019-04-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0002_auto_20190322_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaminants',
            name='contaminant_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
