# Generated by Django 2.2 on 2019-04-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0003_auto_20190405_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State_Avg_Levels',
            new_name='StateAvgLevels',
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.State')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Counties')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.State')),
            ],
        ),
    ]
