# Generated by Django 2.2 on 2019-04-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0004_auto_20190408_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='sources',
            name='county',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Counties'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States'),
        ),
        migrations.AlterField(
            model_name='counties',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='state',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States'),
        ),
        migrations.AlterField(
            model_name='stateavglevels',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.States'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
