# Generated by Django 2.2.1 on 2019-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0004_auto_20190502_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
