# Generated by Django 2.2 on 2019-04-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0004_auto_20190429_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelevels',
            name='contaminant_level',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stateavglevels',
            name='state_avg',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
