# Generated by Django 2.2 on 2019-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0005_auto_20190429_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
