# Generated by Django 2.2 on 2019-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0005_auto_20190417_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contaminants',
            name='contaminant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='counties',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sources',
            name='source_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
