# Generated by Django 2.2 on 2019-04-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0006_auto_20190423_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='county_id',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='sourcelevels',
            old_name='contaminant_id',
            new_name='contaminant',
        ),
        migrations.RenameField(
            model_name='sourcelevels',
            old_name='source_id',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='stateavglevels',
            old_name='contaminant_id',
            new_name='contaminant',
        ),
        migrations.RenameField(
            model_name='stateavglevels',
            old_name='state_id',
            new_name='state',
        ),
    ]
