# Generated by Django 2.2 on 2019-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0007_auto_20190423_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaminants',
            name='health_concerns',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contaminants',
            name='health_guideline',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contaminants',
            name='legal_limit',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contaminants',
            name='long_health_concerns',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contaminants',
            name='national_avg',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contaminants',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
