# Generated by Django 2.2 on 2019-05-01 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vodaMainApp', '0008_auto_20190426_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='score',
        ),
        migrations.AddField(
            model_name='sources',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sourcelevels',
            name='contaminant_level',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='city',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vodaMainApp.Cities'),
        ),
        migrations.AlterField(
            model_name='stateavglevels',
            name='state_avg',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
